routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['prefix' => '/', 'user.', 'namespace' => 'User'], function () {
    Auth::routes();

    Route::get('/', function () {
        if (Auth::check()) {
            return redirect()->route('home');
        } else {
            return view('user.auth.login');
        }
    });

    Route::get('slack/login', 'Auth\AuthenticateController@callSlackApi');
    Route::get('callback', 'Auth\AuthenticateController@loginBySlackUserInfo');

    Route::post('/register', 'Auth\RegisterController@register');
    Route::get('/register/{query}', 'Auth\RegisterController@showRegistrationForm');


    Route::get('home', 'UserController@index')->name('home');

    Route::get('attendance', ['as' => 'attendance.index', 'uses' => 'AttendanceController@index']);
    Route::post('attendance/register', ['as' => 'attendance.register.start', 'uses' => 'AttendanceController@setStartTime']);
    Route::put('attendance/{id}/register', ['as' => 'attendance.register.end', 'uses' => 'AttendanceController@setEndTime']);
    Route::get('attendance/absence', ['as' => 'attendance.absence', 'uses' => 'AttendanceController@showAbsenceForm']);
    Route::post('attendance/absence', ['as' => 'attendance.absence.store', 'uses' => 'AttendanceController@registerAbsence']);
    Route::get('attendance/modify', ['as' => 'attendance.modify', 'uses' => 'AttendanceController@showModifyForm']);
    Route::post('attendance/modify', ['as' => 'attendance.modify.store', 'uses' => 'AttendanceController@storeModifyRequest']);
    Route::get('attendance/mypage', ['as' => 'attendance.mypage', 'uses' => 'AttendanceController@showMypage']);

    Route::resource('report', DailyReportController::class);

    Route::get('question/{id}/mypage', ['as' => 'question.mypage', 'uses' => 'QuestionController@myPage']);
    Route::post('question/confirm', ['as' => 'question.confirm', 'uses' => 'QuestionController@confirm']);
    Route::post('question/{id}/confirm', ['as' => 'confirm.update', 'uses' => 'QuestionController@confirm']);
    Route::post('question/{id}/comment', ['as' => 'question.comment', 'uses' => 'QuestionController@storeComment']);
    Route::resource('question', QuestionController::class);

});


Route::group(['prefix' => 'admin', 'as' => 'admin.' ,'namespace' => 'Admin'], function() {
    Auth::routes();

    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

    Route::resource('report', DailyReportController::class, ['only' => ['index', 'show']]);
    Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

    Route::get('attendance', ['as' => 'attendance.index', 'uses' => 'AttendanceController@index']);
    Route::get('attendance/{id}/user', ['as' => 'attendance.user', 'uses' => 'AttendanceController@user']);
    Route::get('attendance/{id}/user/create', ['as' => 'attendance.user.create', 'uses' => 'AttendanceController@create']);
    Route::get('attendance/{id}/user/edit/{date}', ['as' => 'attendance.user.edit', 'uses' => 'AttendanceController@edit']);
    Route::post('attendance/{id}/user', ['as' => 'attendance.user.store', 'uses' => 'AttendanceController@store']);
    Route::put('attendance/{id}/user', ['as' => 'attendance.user.update', 'uses' => 'AttendanceController@update']);
    Route::get('report', ['as' => 'report.index', 'uses' => 'DailyReportController@index']);
    Route::get('report/{id}/show', ['as' => 'report.show', 'uses' => 'DailyReportController@show']);

    Route::get('question', function () {
        abort(404);
    });

    Route::get('user', function () {
        abort(404);
    });

    Route::get('adminuser', function () {
        abort(404);
    });

    Route::get('contact', function () {
        abort(404);
    });

    Route::post('password/email',['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset',['as' => 'password.request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/reset', ['as' => 'password.request', 'uses' => 'Auth\ResetPasswordController@reset']);
    Route::get('password/reset/{token}', ['as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);

    Route::post('/register', ['as' => 'register', 'uses' => 'Auth\AdminRegisterController@adminRegister']);
    Route::get('/register/', 'Auth\AdminRegisterController@showAdminRegistrationForm');

});

app/Models/Attendance.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\User;
use App\Services\SearchingScope;

class Attendance extends Model
{
    use SearchingScope;

    protected $table = 'attendance';

    public $timestamps = false;

    protected $dates = [
        'start_time',
        'end_time',
        'date',
    ];

    protected $fillable = [
        'user_id',
        'start_time',
        'end_time',
        'request_content',
        'absent_flg',
        'absent_reason',
        'date',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function report()
    {
        return $this->hasOne(DailyReport::class, 'reporting_time', 'date');
    }

    public function fetchSpecificDay($user_id, $date)
    {
        return $this->where('user_id', $user_id)
                    ->where('date', $date->format('Y-m-d'))
                    ->first();
    }

    public function fetchPersonalRecords($user_id)
    {
        return $this->where('user_id', $user_id)
                    ->orderBy('date', 'desc')
                    ->get();
    }

    public function registerStartTime($inputs)
    {
        $hasntRecord = $this->where('user_id', $inputs['user_id'])
                            ->where('date', $inputs['date'])
                            ->doesntExist();
        if ($hasntRecord) {
            $this->create($inputs);
        }
    }

    public function registerAbsence($inputs)
    {
        $this->updateOrCreate(
            ['user_id' => $inputs['user_id'], 'date' => $inputs['date']], $inputs
        );
    }

    public function registerModifyRequest($inputs)
    {
        $this->filterEqual('user_id', $inputs['user_id'])
             ->filterEqual('date', $inputs['date'])
             ->firstOrFail()
             ->fill($inputs)
             ->save();
    }

}

app/Http/Controllers/Admin/AttendanceController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Attendance;
use App\Http\Requests\AttendanceRequest;
use Auth;
use App\Services\CalcDate;

class AttendanceController extends Controller
{
    protected $user;
    protected $attendance;
    protected $calc;

    public function __construct(User $user, Attendance $attendance, CalcDate $calc)
    {
        $this->middleware('auth:admin');
        $this->user = $user;
        $this->attendance = $attendance;
        $this->calc = $calc;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $userInfos = $this->user->all();
        return view('admin.attendance.index', compact('userInfos'));
    }

    /**
     * @param $userId
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function user($userId)
    {
        $userInfo = $this->user->find($userId);
        $absentLateCount = $this->calc->calcAbsentLate($userInfo);
        return view('admin.attendance.user', compact('userInfo', 'absentLateCount'));
    }

    /**
     * @param $userId
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create($userId)
    {
        $userInfo = $this->user->find($userId);
        return view('admin.attendance.create', compact('userInfo'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $inputs = $request->all();
        $inputs = $this->calc->makeDatetimeCarbon($inputs);
        $this->attendance->create($inputs);
        return redirect()->route('admin.attendance.user', $inputs['user_id']);
    }

    /**
     * @param $userId
     * @param $date
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($userId, $date)
    {
        $date = $this->calc->convertStrToCarbon($date);
        $attendance = $this->attendance->fetchSpecificDay($userId, $date);
        return view('admin.attendance.edit', compact('userInfo', 'attendance'));
    }

    /**
     * @param Request $request
     * @param $userId
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $userId)
    {
        $inputs = $request->all();
        $inputs = $this->calc->makeDatetimeCarbon($inputs);
        $this->attendance->find($inputs['id'])->fill($inputs)->save();
        return redirect()->route('admin.attendance.user', $userId);
    }

}

app/Http/Controllers/User/AttendanceController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\AttendanceRequest;
use App\Models\Attendance;
use App\Services\CalcDate;
use Illuminate\Support\Facades\Auth;

class AttendanceController extends Controller
{
    protected $attendance;
    protected $calc;

    public function __construct(Attendance $attendance, CalcDate $calc)
    {
        $this->middleware('auth');
        $this->attendance = $attendance;
        $this->calc = $calc;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $userId = Auth::id();
        $attendance = $this->attendance->fetchSpecificDay($userId, $this->calc->today);
        return view('user.attendance.index', compact('attendance'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function showAbsenceForm()
    {
        return view('user.attendance.absence');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function showModifyForm()
    {
        return view('user.attendance.modify');
    }

    /**
     * @param CalcDate $calcDate
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function showMypage(CalcDate $calcDate)
    {
        $userId = Auth::id();
        $workInfos = $this->attendance->fetchPersonalRecords($userId);
        $dateSum = $calcDate->calcDatetimeSum($workInfos);
        return view('user.attendance.mypage', compact('workInfos', 'dateSum'));
    }

    /**
     * @param AttendanceRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function setStartTime(AttendanceRequest $request)
    {
        $inputs = $request->all();
        $this->attendance->registerStartTime($inputs);
        return redirect()->route('attendance.index');
    }

    /**
     * @param AttendanceRequest $request
     * @param $recordId
     * @return \Illuminate\Http\RedirectResponse
     */
    public function setEndTime(AttendanceRequest $request, $recordId)
    {
        $inputs = $request->all();
        $this->attendance->find($recordId)->fill($inputs)->save();
        return redirect()->route('attendance.index');
    }

    /**
     * @param AttendanceRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function registerAbsence(AttendanceRequest $request)
    {
        $inputs = $request->all();
        $this->attendance->registerAbsence($inputs);
        return redirect()->route('attendance.index');
    }

    /**
     * @param AttendanceRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function storeModifyRequest(AttendanceRequest $request)
    {
        $inputs = $request->all();
        $this->attendance->registerModifyRequest($inputs);
        return redirect()->route('attendance.index');
    }

}

resources/views/admin/attendance/create.blade.php
@extends ('common.admin')
@section ('content')

<h2 class="brand-header">個別勤怠作成</h2>
<div class="main-wrap">
  <div class="user-info-box clearfix">
    <div class="left-info">
      <img src="{{ $userInfo->avatar }}"><p class="user-name">{{ $userInfo->name }}</p>
      <i class="fa fa-envelope-o" aria-hidden="true"><p class="user-email">{{ $userInfo->email }}</p></i>
    </div>
    <div class="right-info">
      <div class="my-info">
        <p>研修開始日</p>
        <div class="study-hour-box clearfix">
          <p class="study-hour study-date"><span>{{ $userInfo->created_at->format('Y/m/d') }}</span></p>
        </div>
      </div>
    </div>
  </div>

  <div class="attendance-modify-box">
    {!! Form::open(['route' => ['admin.attendance.user.update', $userInfo->id], 'method' => 'post']) !!}
      {!! Form::input('hidden', 'user_id', $userInfo->id) !!}
      <div class="form-group date-form">
        {!! Form::input('date', 'date', null, ['class' => 'form-control']) !!}
      </div>
      <div class="form-group">
        {!! Form::input('time', 'start_time', null, ['class' => 'form-control']) !!}
      </div>
      <p class="to-time">to</p>
      <div class="form-group">
        {!! Form::input('time', 'end_time', null, ['class' => 'form-control']) !!}
      </div>
      {!! Form::button('作成', ['class' => 'btn btn-modify', 'type' => 'submit']) !!}
    {!! Form::close() !!}
    {!! Form::open(['route' => ['admin.attendance.user.update', $userInfo->id], 'method' => 'post']) !!}
      {!! Form::input('hidden', 'user_id', $userInfo->id) !!}
      {!! Form::input('hidden', 'start_time', null) !!}
      {!! Form::input('hidden', 'end_time', null) !!}
      {!! Form::input('hidden', 'absent_flg', 1) !!}
      {!! Form::input('hidden', 'absent_reason', '管理画面から登録') !!}
      {!! Form::input('hidden', 'date', null, ['id' => 'date-target']) !!}
      {!! Form::button('欠席', ['class' => 'btn btn-danger', 'type' => 'submit']) !!}
    {!! Form::close() !!}
  </div>

</div>

@endsection

resources/views/admin/attendance/edit.blade.php
@extends ('common.admin')
@section ('content')

<h2 class="brand-header">個別勤怠編集</h2>
<div class="main-wrap">
  <div class="user-info-box clearfix">
    <div class="left-info">
      <img src="{{ $attendance->user->avatar }}"><p class="user-name">{{ $attendance->user->name }}</p>
      <i class="fa fa-envelope-o" aria-hidden="true"><p class="user-email">{{ $attendance->user->email }}</p></i>
    </div>
    <div class="right-info">
      <div class="my-info day-info">
        <p>編集日</p>
        <div class="study-hour-box clearfix">
          <div class="userinfo-box"><i class="fa fa-calendar fa-2x" aria-hidden="true"></i></div>
          <p class="study-hour study-date"><span>{{ $attendance->date->format('m/d') }}</span></p>
        </div>
      </div>
      <div class="my-info">
        <p>研修開始日</p>
        <div class="study-hour-box clearfix">
          <p class="study-hour study-date"><span>{{ $attendance->user->created_at->format('Y/m/d') }}</span></p>
        </div>
      </div>
    </div>
  </div>
  @if ($attendance->absent_flg)
    <div class="request-box">
      <div class="request-title">
        <img src="{{ $attendance->user->avatar }}" class="avatar-img">
        <p class="absent">欠席理由</p>
      </div>
      <div class="request-content">{{ $attendance->absent_reason }}</div>
    </div>
  @endif
  @if (!empty($attendance->request_content))
    <div class="request-box">
      <div class="request-title">
        <img src="{{ $attendance->user->avatar }}" class="avatar-img">
        <p>修正申請内容</p>
      </div>
      <div class="request-content">{{ $attendance->request_content }}</div>
    </div>
  @endif

  <div class="attendance-modify-box">
    {!! Form::open(['route' => ['admin.attendance.user.update', $attendance->user->id], 'method' => 'put']) !!}
      {!! Form::input('hidden', 'id', $attendance->id) !!}
      {!! Form::input('hidden', 'date', $attendance->date->format('Y-m-d')) !!}
      {!! Form::input('hidden', 'request_content', null) !!}
      {!! Form::input('hidden', 'absent_flg', 0) !!}
      {!! Form::input('hidden', 'absent_reason', null) !!}
      <div class="form-group {{ $errors->has('start_time') ? 'has-error' : '' }}">
        @if (empty($attendance->start_time))
          {!! Form::input('time', 'start_time', null, ['class' => 'form-control']) !!}
        @else
          {!! Form::input('time', 'start_time', $attendance->start_time->format('H:i'), ['class' => 'form-control']) !!}
        @endif
        <span class="help-block">{{ $errors->first('content') }}</span>
      </div>
      <p class="to-time">to</p>
      <div class="form-group {{ $errors->has('end_time') ? 'has-error' : '' }}">
        @if (empty($attendance->end_time))
          {!! Form::input('time', 'end_time', null, ['class' => 'form-control']) !!}
        @else
          {!! Form::input('time', 'end_time', $attendance->end_time->format('H:i'), ['class' => 'form-control']) !!}
        @endif
        <span class="help-block">{{ $errors->first('content') }}</span>
      </div>
      <button type="submit" class="btn btn-modify">修正</button>
    {!! Form::close() !!}
    {!! Form::open(['route' => ['admin.attendance.user.update', $attendance->user->id], 'method' => 'put']) !!}
      {!! Form::input('hidden', 'id', $attendance->id) !!}
      {!! Form::input('hidden', 'start_time', null) !!}
      {!! Form::input('hidden', 'end_time', null) !!}
      {!! Form::input('hidden', 'request_content', null) !!}
      {!! Form::input('hidden', 'absent_flg', 1) !!}
      {!! Form::input('hidden', 'absent_reason', '管理画面から登録') !!}
      {!! Form::input('hidden', 'date', $attendance->date->format('Y-m-d')) !!}
      <button type="submit" class="btn btn-danger">欠席</button>
    {!! Form::close() !!}
  </div>

</div>

@endsection

resources/views/admin/attendance/index.blade.php
@extends ('common.admin')
@section ('content')

<h2 class="brand-header">勤怠情報</h2>
<div class="main-wrap">
  <div class="btn-wrapper">
    <div class="my-info day-info">
      <p>想定出席人数</p>
      <div class="study-hour-box clearfix">
        <div class="userinfo-box"><i class="fa fa-user fa-2x" aria-hidden="true"></i></div>
        <p class="study-hour"><span>{{ count($userInfos) }}</span>人</p>
      </div>
    </div>
  </div>
  <div class="content-wrapper table-responsive">
    <table class="table">
      <caption><p>出社済み</p></caption>
      <thead>
        <tr class="row">
          <th class="col-xs-1"></th>
          <th class="col-xs-2">名前</th>
          <th class="col-xs-2">研修開始日</th>
          <th class="col-xs-3">出社時間</th>
          <th class="col-xs-2">修正申請</th>
          <th class="col-xs-2">詳細</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($userInfos as $userInfo)
          @if (!empty($userInfo->attendance) && !$userInfo->attendance->absent_flg)
            <tr class="row">
              <td class="col-xs-1"><img src="{{ $userInfo->avatar }}" class="avatar-img"></td>
              <td class="col-xs-2">{{ $userInfo->name }}</td>
              <td class="col-xs-2">{{ $userInfo->created_at->format('Y/m/d') }}</td>
              <td class="col-xs-3">{{ $userInfo->attendance->start_time->format('H:i') }}</td>
              <td class="col-xs-2">-</td>
              <td class="col-xs-2"><a href="{{ route('admin.attendance.user', $userInfo->id) }}" class="btn btn-sucssess"><i class="fa fa-file-text-o" aria-hidden="true"></i></a></td>
            </tr>
          @endif
        @endforeach
      </tbody>
    </table>
  </div>
  <div class="content-wrapper table-responsive attendance-table">
    <table class="table">
      <caption><p class="still">出社未登録</p></caption>
      <thead>
        <tr class="row">
          <th class="col-xs-1"></th>
          <th class="col-xs-4">名前</th>
          <th class="col-xs-4">研修開始日</th>
          <th class="col-xs-3">詳細</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($userInfos as $userInfo)
          @if (empty($userInfo->attendance))
            <tr class="row">
              <td class="col-xs-1"><img src="{{ $userInfo->avatar }}" class="avatar-img"></td>
              <td class="col-xs-4">{{ $userInfo->name }}</td>
              <td class="col-xs-4">{{ $userInfo->created_at->format('Y/m/d') }}</td>
              <td class="col-xs-3"><a href="{{ route('admin.attendance.user', $userInfo->id) }}" class="btn btn-sucssess"><i class="fa fa-file-text-o" aria-hidden="true"></i></a></td>
            </tr>
          @endif
        @endforeach
      </tbody>
    </table>
  </div>
  <div class="content-wrapper table-responsive attendance-table">
    <table class="table">
      <caption><p class="absence">欠席</p></caption>
      <thead>
        <tr class="row">
          <th class="col-xs-1"></th>
          <th class="col-xs-4">名前</th>
          <th class="col-xs-4">研修開始日</th>
          <th class="col-xs-3">詳細</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($userInfos as $userInfo)
          @if (!empty($userInfo->attendance) && $userInfo->attendance->absent_flg)
            <tr class="row">
              <td class="col-xs-1"><img src="{{ $userInfo->avatar }}" class="avatar-img"></td>
              <td class="col-xs-4">{{ $userInfo->name }}</td>
              <td class="col-xs-4">{{ $userInfo->created_at->format('Y/m/d') }}</td>
              <td class="col-xs-3"><a href="{{ route('admin.attendance.user', $userInfo->id) }}" class="btn btn-sucssess"><i class="fa fa-file-text-o" aria-hidden="true"></i></a></td>
            </tr>
          @endif
        @endforeach
      </tbody>
    </table>
  </div>

</div>

@endsection

resources/views/admin/attendance/user.blade.php
@extends ('common.admin')
@section ('content')

<h2 class="brand-header">個別勤怠管理</h2>
<div class="main-wrap">
  <div class="user-info-box clearfix">
    <div class="left-info">
      <img src="{{ $userInfo->avatar }}"><p class="user-name">{{ $userInfo->name }}</p>
      <i class="fa fa-envelope-o" aria-hidden="true"><p class="user-email">{{ $userInfo->email }}</p></i>
    </div>
    <div class="right-info">
      <div class="my-info absence-info">
        <p>欠席回数</p>
        <div class="study-hour-box clearfix">
          <div class="userinfo-box"><i class="fa fa-ban fa-2x" aria-hidden="true"></i></div>
          <p class="study-hour"><span>{{ $absentLateCount['absentCount'] }}</span>回</p>
        </div>
      </div>
      <div class="my-info day-info">
        <p>遅刻回数</p>
        <div class="study-hour-box clearfix">
          <div class="userinfo-box"><i class="fa fa-clock-o fa-2x" aria-hidden="true"></i></div>
          <p class="study-hour"><span>{{ $absentLateCount['lateCount'] }}</span>回</p>
        </div>
      </div>
      <div class="my-info">
        <p>研修開始日</p>
        <div class="study-hour-box clearfix">
          <p class="study-hour study-date"><span>{{ $userInfo->created_at->format('Y/m/d') }}</span></p>
        </div>
      </div>
    </div>
  </div>

  <div class="btn-wrapper">
    <a href="{{ route('admin.attendance.user.create', $userInfo->id) }}" class="btn btn-icon">
      <i class="fa fa-plus" aria-hidden="true"></i>
    </a>
  </div>
  <div class="content-wrapper table-responsive">
    <table class="table">
      <thead>
        <tr class="row">
          <th class="col-xs-1">日付</th>
          <th class="col-xs-1">曜日</th>
          <th class="col-xs-2">状態</th>
          <th class="col-xs-2">出社時間</th>
          <th class="col-xs-2">退社時間</th>
          <th class="col-xs-2">修正申請</th>
          <th class="col-xs-2">修正</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($userInfo->allAttendance as $attendance)
          @if (!empty($attendance))
            <tr class="row {{ $attendance->absent_flg ? 'absent-row' : '' }}">
              <td class="col-xs-1">{{ $attendance->date->format('m/d') }}</td>
              <td class="col-xs-1">{{ $attendance->date->format('D') }}</td>
              @if ($attendance->absent_flg)
                <td class="col-xs-2">欠席</span></td>
              @elseif ($attendance->date == Carbon::today() && empty($attendance->end_time))
                <td class="col-xs-2">研修中</td>
              @else
                <td class="col-xs-2">出社</td>
              @endif
              @if (empty($attendance->start_time))
                <td class="col-xs-2">-</td>
              @else
                <td class="col-xs-2">{{ $attendance->start_time->format('H:i') }}</td>
              @endif
              @if (empty($attendance->end_time))
                <td class="col-xs-2">-</td>
              @else
                <td class="col-xs-2">{{ $attendance->end_time->format('H:i') }}</td>
              @endif
              @if (empty($attendance->request_content))
                <td class="col-xs-2">-</td>
              @else
                <td class="col-xs-2"><span class="attention">あり</span></td>
              @endif
              <td class="col-xs-2">
                <a href="{{ route('admin.attendance.user.edit', [$userInfo->id, $attendance->date->format('Y-m-d')]) }}" class="btn btn-sucssess btn-small">
                  <i class="fa fa-pencil" aria-hidden="true"></i>
                </a>
              </td>
            </tr>
          @endif
        @endforeach
      </tbody>
    </table>
  </div>


</div>

@endsection