routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['prefix' => '/', 'user.', 'namespace' => 'User'], function () {
    Auth::routes();

    Route::get('/', function () {
        if (Auth::check()) {
            return redirect()->route('home');
        } else {
            return view('user.auth.login');
        }
    });

    Route::get('slack/login', 'Auth\AuthenticateController@callSlackApi');
    Route::get('callback', 'Auth\AuthenticateController@loginBySlackUserInfo');

    Route::post('/register', 'Auth\RegisterController@register');
    Route::get('/register/{query}', 'Auth\RegisterController@showRegistrationForm');


    Route::get('home', 'UserController@index')->name('home');

    Route::get('attendance', ['as' => 'attendance.index', 'uses' => 'AttendanceController@index']);
    Route::post('attendance/register', ['as' => 'attendance.register.start', 'uses' => 'AttendanceController@setStartTime']);
    Route::put('attendance/{id}/register', ['as' => 'attendance.register.end', 'uses' => 'AttendanceController@setEndTime']);
    Route::get('attendance/absence', ['as' => 'attendance.absence', 'uses' => 'AttendanceController@showAbsenceForm']);
    Route::post('attendance/absence', ['as' => 'attendance.absence.store', 'uses' => 'AttendanceController@registerAbsence']);
    Route::get('attendance/modify', ['as' => 'attendance.modify', 'uses' => 'AttendanceController@showModifyForm']);
    Route::post('attendance/modify', ['as' => 'attendance.modify.store', 'uses' => 'AttendanceController@storeModifyRequest']);
    Route::get('attendance/mypage', ['as' => 'attendance.mypage', 'uses' => 'AttendanceController@showMypage']);

    Route::resource('report', DailyReportController::class);

    Route::get('question/{id}/mypage', ['as' => 'question.mypage', 'uses' => 'QuestionController@myPage']);
    Route::post('question/confirm', ['as' => 'question.confirm', 'uses' => 'QuestionController@confirm']);
    Route::post('question/{id}/confirm', ['as' => 'confirm.update', 'uses' => 'QuestionController@confirm']);
    Route::post('question/{id}/comment', ['as' => 'question.comment', 'uses' => 'QuestionController@storeComment']);
    Route::resource('question', QuestionController::class);

});


Route::group(['prefix' => 'admin', 'as' => 'admin.' ,'namespace' => 'Admin'], function() {
    Auth::routes();

    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

    Route::resource('report', DailyReportController::class, ['only' => ['index', 'show']]);
    Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

    Route::get('attendance', ['as' => 'attendance.index', 'uses' => 'AttendanceController@index']);
    Route::get('attendance/{id}/user', ['as' => 'attendance.user', 'uses' => 'AttendanceController@user']);
    Route::get('attendance/{id}/user/create', ['as' => 'attendance.user.create', 'uses' => 'AttendanceController@create']);
    Route::get('attendance/{id}/user/edit/{date}', ['as' => 'attendance.user.edit', 'uses' => 'AttendanceController@edit']);
    Route::post('attendance/{id}/user', ['as' => 'attendance.user.store', 'uses' => 'AttendanceController@store']);
    Route::put('attendance/{id}/user', ['as' => 'attendance.user.update', 'uses' => 'AttendanceController@update']);
    Route::get('report', ['as' => 'report.index', 'uses' => 'DailyReportController@index']);
    Route::get('report/{id}/show', ['as' => 'report.show', 'uses' => 'DailyReportController@show']);

    Route::get('question', function () {
        abort(404);
    });

    Route::get('user', function () {
        abort(404);
    });

    Route::get('adminuser', function () {
        abort(404);
    });

    Route::get('contact', function () {
        abort(404);
    });

    Route::post('password/email',['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset',['as' => 'password.request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/reset', ['as' => 'password.request', 'uses' => 'Auth\ResetPasswordController@reset']);
    Route::get('password/reset/{token}', ['as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm']);

    Route::post('/register', ['as' => 'register', 'uses' => 'Auth\AdminRegisterController@adminRegister']);
    Route::get('/register/', 'Auth\AdminRegisterController@showAdminRegistrationForm');

});

app/Models/DailyReport.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Services\SearchingScope;
use App\Models\User;

class DailyReport extends Model
{
    use SoftDeletes, SearchingScope;

    protected $fillable = [
        'user_id',
        'title',
        'contents',
        'reporting_time',
    ];

    protected $dates = [
        'reporting_time',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    // SearchingScope traitに定義されている検索用scopeを使用
    public function fetchAllPersonalReports($userId)
    {
        return $this->filterEqual('user_id', $userId)
                    ->orderby('reporting_time', 'desc')
                    ->get();
    }

    // SearchingScope traitに定義されている検索用scopeを使用
    public function fetchSearchingPersonalReports($userId, $serchConditions)
    {
        return $this->filterEqual('user_id', $userId)
                    ->filterLike('reporting_time', $serchConditions['search-month'])
                    ->orderby('reporting_time', 'desc')
                    ->get();
    }

}

app/Http/Controllers/Admin/DailyReportController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\DailyReport;
use App\Models\User;
use App\Services\CalcDate;

class DailyReportController extends Controller
{
    protected $user;
    protected $report;

    public function __construct(User $user, DailyReport $report, CalcDate $calc)
    {
        $this->middleware('auth:admin');
        $this->user = $user;
        $this->report = $report;
        $this->calc = $calc;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $users = $this->user->all();
        return view('admin.daily_report.index', compact('users'));
    }

    /**
     * @param $userId
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($userId)
    {
        $reports = $this->report->fetchAllPersonalReports($userId);
        return view('admin.daily_report.show', compact('reports'));
    }
}

app/Http/Controllers/User/DailyReportController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\DailyReportRequest;
use App\Models\DailyReport;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DailyReportController extends Controller
{
    protected $report;

    public function __construct(DailyReport $report)
    {
        $this->middleware('auth');
        $this->report = $report;
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $userId = Auth::id();
        $inputs = $request->all();

        if (empty($inputs)) {
            $reports = $this->report->fetchAllPersonalReports($userId);
        } else {
            $reports = $this->report->fetchSearchingPersonalReports($userId, $inputs);
        }
        return view('user.daily_report.index', compact('reports', 'inputs'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('user.daily_report.create');
    }

    /**
     * @param DailyReportRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(DailyReportRequest $request)
    {
        $inputs = $request->all();
        $this->report->create($inputs);
        return redirect()->to('report');
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $report = $this->report->find($id);
        return view('user.daily_report.show', compact('report'));
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $report = $this->report->find($id);
        return view('user.daily_report.edit', compact('report'));
    }

    /**
     * @param DailyReportRequest $request
     * @param $reportId
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(DailyReportRequest $request, $reportId)
    {
        $inputs = $request->all();
        $this->report->find($reportId)->fill($inputs)->save();
        return redirect()->to('report');
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $this->report->find($id)->delete();
        return redirect()->to('report');
    }

}

resources/views/admin/daily_report/index.blade.php
@extends ('common.admin')
@section ('content')

<h2 class="brand-header">日報一覧</h2>
<div class="main-wrap clearfix">


  <div class="left-box">
    <div class="content-wrapper table-responsive">
      <table class="table">
        <caption><p>本日の日報</p></caption>
        <thead>
          <tr class="row">
            <th class="col-xs-1"></th>
            <th class="col-xs-4">名前</th>
            <th class="col-xs-5">タイトル</th>
            <th class="col-xs-2">詳細</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($users as $user)
            @if (!empty($user->attendance) && !empty($user->attendance->report))
              <tr class="row">
                <td class="col-xs-1"><img src="{{ $user->avatar }}" class="avatar-img"></td>
                <td class="col-xs-4">{{ $user->name }}</td>
                <td class="col-xs-5">{{ $user->attendance->report->title }}</td>
                <td class="col-xs-2">
                  <a href="{{ route('admin.report.show', $user->id) }}" class="btn btn-sucssess">
                    <i class="fa fa-file-text-o" aria-hidden="true"></i>
                  </a>
                </td>
              </tr>
            @else
              <tr class="row">
                <td class="col-xs-1"><img src="{{ $user->avatar }}" class="avatar-img"></td>
                <td class="col-xs-4">{{ $user->name }}</td>
                <td class="col-xs-5">未提出</td>
                <td class="col-xs-2"><i class="fa fa-times" aria-hidden="true"></i></td>
              </tr>
            @endif
          @endforeach
        </tbody>
      </table>
    </div>
  </div>

  <div class="right-box">
    <div class="right-parts table-responsive">
      <table class="table">
        <caption>日報未提出者</caption>
        <tbody>
          @foreach ($users as $user)
            @if (!empty($user->attendance) && empty($user->attendance->report) && !$user->attendance->absent_flg)
              <tr class="row">
                <td class="col-xs-2"><img src="{{ $user->avatar }}" class="avatar-img"></td>
                <td class="col-xs-5">
                  <a href="{{ route('admin.report.show', $user->id) }}">{{ $user->name }}</a>
                </td>
                <td class="col-xs-3">{{ $user->created_at->format('m/d') }}&nbsp;~</td>
              </tr>
            @endif
          @endforeach
        </tbody>
      </table>
    </div>

    <div class="right-parts absent table-responsive">
      <table class="table">
        <caption>欠席者</caption>
        <tbody>
          @foreach ($users as $user)
            @if (!empty($user->attendance) && $user->attendance->absent_flg)
              <tr class="row">
                <td class="col-xs-2"><img src="{{ $user->avatar }}" class="avatar-img"></td>
                <td class="col-xs-5">
                  <a class="{{ route('admin.report.show', $user->id) }}">{{ $user->name }}</a>
                </td>
                <td class="col-xs-3">{{ $user->created_at->format('m/d') }}&nbsp;~</td>
              </tr>
            @endif
          @endforeach
        </tbody>
      </table>
    </div>
  </div>


</div>

@endsection

resources/views/admin/daily_report/show.blade.php
@extends ('common.admin')
@section ('content')

<h2 class="brand-header">個別日報一覧</h2>
<div class="main-wrap admin-report">

  @foreach ($reports as $report)
    <div class="panel panel-success">
      <div class="panel-heading">
        <img src="{{ $report->user->avatar }}" class="avatar-img">
        <p>{{ $report->reporting_time->format('Y/m/d (D)') }} の日報</p>
      </div>
      <div class="table-responsive">
        <table class="table table-striped table-bordered">
          <tbody>
            <tr>
              <th class="table-column">Title</th>
              <td class="td-text">{{ $report->title }}</td>
            </tr>
            <tr>
              <th class="table-column">Content</th>
              <td class='td-text'>{!! nl2br(e($report->contents)) !!}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  @endforeach

</div>

@endsection